function [ sensitivity,...
           specificity,...
           dice_coefficient,...
           jaccard_similarity, ...
           precision, ...
           recall, ...
           f1_score ...
          ] = calculate_metrics ( true_positives,...
                                  true_negatives,...
                                  false_positives,...
                                  false_negatives )



    sensitivity        = true_positives / (true_positives + false_negatives);

    specificity       = true_negatives / (true_negatives + false_positives);

    dice_coefficient   = 2 * true_positives / ((false_positives + true_positives) + (true_positives + false_negatives));

    jaccard_similarity = true_positives / (false_positives + true_positives + false_negatives);

    precision          = true_positives / (true_positives + false_positives);

    recall             = true_positives / (true_positives + false_negatives); 

    f1_score           = 2 * (precision * recall) / (precision + recall);



end

