% batch script to test multiple versions of growcut in t1, t1Gad, t2 and FLAIR channels

% # of datasets from BRATS 2012 considered
numberOfTestCases = 10;

%vezhnevets's growcut stats
dice_coefficient_tumor_vezhnevets = single(zeros(numberOfTestCases, 1));
sensitivity_tumor_vezhnevets      = single(zeros(numberOfTestCases, 1));
precision_tumor_vezhnevets        = single(zeros(numberOfTestCases, 1));
specificity_tumor_vezhnevets      = single(zeros(numberOfTestCases, 1));
    
dice_coefficient_edema_vezhnevets = single(zeros(numberOfTestCases, 1));
sensitivity_edema_vezhnevets      = single(zeros(numberOfTestCases, 1));
precision_edema_vezhnevets        = single(zeros(numberOfTestCases, 1));
specificity_edema_vezhnevets      = single(zeros(numberOfTestCases, 1)); 

steps_vezhnevets                  = single(zeros(numberOfTestCases,1));
execution_time_vezhnevets         = single(zeros(numberOfTestCases,1));

%corrected growcut stats
dice_coefficient_tumor_corrected = single(zeros(numberOfTestCases, 1));
sensitivity_tumor_corrected      = single(zeros(numberOfTestCases, 1));
precision_tumor_corrected        = single(zeros(numberOfTestCases, 1));
specificity_tumor_corrected      = single(zeros(numberOfTestCases, 1));
    
dice_coefficient_edema_corrected = single(zeros(numberOfTestCases, 1));
sensitivity_edema_corrected      = single(zeros(numberOfTestCases, 1));
precision_edema_corrected        = single(zeros(numberOfTestCases, 1));
specificity_edema_corrected      = single(zeros(numberOfTestCases, 1)); 

steps_corrected                  = single(zeros(numberOfTestCases,1));
execution_time_corrected         = single(zeros(numberOfTestCases,1));


%growcut with exponential penalty to attack strength stats, nsdevs = 1
%stats
dice_coefficient_tumor_exponential_nsdevs_1 = single(zeros(numberOfTestCases, 1));
sensitivity_tumor_exponential_nsdevs_1      = single(zeros(numberOfTestCases, 1));
precision_tumor_exponential_nsdevs_1        = single(zeros(numberOfTestCases, 1));
specificity_tumor_exponential_nsdevs_1      = single(zeros(numberOfTestCases, 1));
    
dice_coefficient_edema_exponential_nsdevs_1 = single(zeros(numberOfTestCases, 1));
sensitivity_edema_exponential_nsdevs_1      = single(zeros(numberOfTestCases, 1));
precision_edema_exponential_nsdevs_1        = single(zeros(numberOfTestCases, 1));
specificity_edema_exponential_nsdevs_1      = single(zeros(numberOfTestCases, 1)); 

steps_exponential_nsdevs_1                  = single(zeros(numberOfTestCases,1));
execution_time_exponential_nsdevs_1         = single(zeros(numberOfTestCases,1));


%growcut with exponential penalty to attack strength stats, nsdevs = 2
dice_coefficient_tumor_exponential_nsdevs_2 = single(zeros(numberOfTestCases, 1));
sensitivity_tumor_exponential_nsdevs_2      = single(zeros(numberOfTestCases, 1));
precision_tumor_exponential_nsdevs_2        = single(zeros(numberOfTestCases, 1));
specificity_tumor_exponential_nsdevs_2      = single(zeros(numberOfTestCases, 1));
    
dice_coefficient_edema_exponential_nsdevs_2 = single(zeros(numberOfTestCases, 1));
sensitivity_edema_exponential_nsdevs_2      = single(zeros(numberOfTestCases, 1));
precision_edema_exponential_nsdevs_2        = single(zeros(numberOfTestCases, 1));
specificity_edema_exponential_nsdevs_2      = single(zeros(numberOfTestCases, 1)); 

steps_exponential_nsdevs_2                  = single(zeros(numberOfTestCases,1));
execution_time_exponential_nsdevs_2         = single(zeros(numberOfTestCases,1));

%growcut with exponential penalty to attack strength stats, nsdevs = 3
dice_coefficient_tumor_exponential_nsdevs_3 = single(zeros(numberOfTestCases, 1));
sensitivity_tumor_exponential_nsdevs_3      = single(zeros(numberOfTestCases, 1));
precision_tumor_exponential_nsdevs_3        = single(zeros(numberOfTestCases, 1));
specificity_tumor_exponential_nsdevs_3      = single(zeros(numberOfTestCases, 1));
    
dice_coefficient_edema_exponential_nsdevs_3 = single(zeros(numberOfTestCases, 1));
sensitivity_edema_exponential_nsdevs_3      = single(zeros(numberOfTestCases, 1));
precision_edema_exponential_nsdevs_3        = single(zeros(numberOfTestCases, 1));
specificity_edema_exponential_nsdevs_3      = single(zeros(numberOfTestCases, 1)); 

steps_exponential_nsdevs_3                  = single(zeros(numberOfTestCases,1));
execution_time_exponential_nsdevs_3         = single(zeros(numberOfTestCases,1));

%growcut with linear penalty to attack strength stats, nsdevs = 1
dice_coefficient_tumor_linear_nsdevs_1 = single(zeros(numberOfTestCases, 1));
sensitivity_tumor_linear_nsdevs_1      = single(zeros(numberOfTestCases, 1));
precision_tumor_linear_nsdevs_1        = single(zeros(numberOfTestCases, 1));
specificity_tumor_linear_nsdevs_1      = single(zeros(numberOfTestCases, 1));
    
dice_coefficient_edema_linear_nsdevs_1 = single(zeros(numberOfTestCases, 1));
sensitivity_edema_linear_nsdevs_1      = single(zeros(numberOfTestCases, 1));
precision_edema_linear_nsdevs_1        = single(zeros(numberOfTestCases, 1));
specificity_edema_linear_nsdevs_1      = single(zeros(numberOfTestCases, 1)); 

steps_linear_nsdevs_1                  = single(zeros(numberOfTestCases,1));
execution_time_linear_nsdevs_1         = single(zeros(numberOfTestCases,1));

%growcut with linear penalty to attack strength stats, nsdevs = 2
dice_coefficient_tumor_linear_nsdevs_2 = single(zeros(numberOfTestCases, 1));
sensitivity_tumor_linear_nsdevs_2      = single(zeros(numberOfTestCases, 1));
precision_tumor_linear_nsdevs_2        = single(zeros(numberOfTestCases, 1));
specificity_tumor_linear_nsdevs_2      = single(zeros(numberOfTestCases, 1));
    
dice_coefficient_edema_linear_nsdevs_2 = single(zeros(numberOfTestCases, 1));
sensitivity_edema_linear_nsdevs_2      = single(zeros(numberOfTestCases, 1));
precision_edema_linear_nsdevs_2        = single(zeros(numberOfTestCases, 1));
specificity_edema_linear_nsdevs_2      = single(zeros(numberOfTestCases, 1)); 

steps_linear_nsdevs_2                  = single(zeros(numberOfTestCases,1));
execution_time_linear_nsdevs_2         = single(zeros(numberOfTestCases,1));

%growcut with linear penalty to attack strength stats, nsdevs = 3
dice_coefficient_tumor_linear_nsdevs_3 = single(zeros(numberOfTestCases, 1));
sensitivity_tumor_linear_nsdevs_3      = single(zeros(numberOfTestCases, 1));
precision_tumor_linear_nsdevs_3        = single(zeros(numberOfTestCases, 1));
specificity_tumor_linear_nsdevs_3      = single(zeros(numberOfTestCases, 1));
    
dice_coefficient_edema_linear_nsdevs_3 = single(zeros(numberOfTestCases, 1));
sensitivity_edema_linear_nsdevs_3      = single(zeros(numberOfTestCases, 1));
precision_edema_linear_nsdevs_3        = single(zeros(numberOfTestCases, 1));
specificity_edema_linear_nsdevs_3      = single(zeros(numberOfTestCases, 1)); 

steps_linear_nsdevs_3                  = single(zeros(numberOfTestCases,1));
execution_time_linear_nsdevs_3         = single(zeros(numberOfTestCases,1));


%growcut with constant penalty to attack strength stats, nsdevs = 1
dice_coefficient_tumor_constant_nsdevs_1 = single(zeros(numberOfTestCases, 1));
sensitivity_tumor_constant_nsdevs_1      = single(zeros(numberOfTestCases, 1));
precision_tumor_constant_nsdevs_1        = single(zeros(numberOfTestCases, 1));
specificity_tumor_constant_nsdevs_1      = single(zeros(numberOfTestCases, 1));
    
dice_coefficient_edema_constant_nsdevs_1 = single(zeros(numberOfTestCases, 1));
sensitivity_edema_constant_nsdevs_1      = single(zeros(numberOfTestCases, 1));
precision_edema_constant_nsdevs_1        = single(zeros(numberOfTestCases, 1));
specificity_edema_constant_nsdevs_1      = single(zeros(numberOfTestCases, 1)); 

steps_constant_nsdevs_1                  = single(zeros(numberOfTestCases,1));
execution_time_constant_nsdevs_1         = single(zeros(numberOfTestCases,1));

%growcut with constant penalty to attack strength stats, nsdevs = 2
dice_coefficient_tumor_constant_nsdevs_2 = single(zeros(numberOfTestCases, 1));
sensitivity_tumor_constant_nsdevs_2      = single(zeros(numberOfTestCases, 1));
precision_tumor_constant_nsdevs_2        = single(zeros(numberOfTestCases, 1));
specificity_tumor_constant_nsdevs_2      = single(zeros(numberOfTestCases, 1));
    
dice_coefficient_edema_constant_nsdevs_2 = single(zeros(numberOfTestCases, 1));
sensitivity_edema_constant_nsdevs_2      = single(zeros(numberOfTestCases, 1));
precision_edema_constant_nsdevs_2        = single(zeros(numberOfTestCases, 1));
specificity_edema_constant_nsdevs_2      = single(zeros(numberOfTestCases, 1)); 

steps_constant_nsdevs_2                  = single(zeros(numberOfTestCases,1));
execution_time_constant_nsdevs_2         = single(zeros(numberOfTestCases,1));

%growcut with constant penalty to attack strength stats, nsdevs = 3
dice_coefficient_tumor_constant_nsdevs_3 = single(zeros(numberOfTestCases, 1));
sensitivity_tumor_constant_nsdevs_3      = single(zeros(numberOfTestCases, 1));
precision_tumor_constant_nsdevs_3        = single(zeros(numberOfTestCases, 1));
specificity_tumor_constant_nsdevs_3      = single(zeros(numberOfTestCases, 1));
    
dice_coefficient_edema_constant_nsdevs_3 = single(zeros(numberOfTestCases, 1));
sensitivity_edema_constant_nsdevs_3      = single(zeros(numberOfTestCases, 1));
precision_edema_constant_nsdevs_3        = single(zeros(numberOfTestCases, 1));
specificity_edema_constant_nsdevs_3      = single(zeros(numberOfTestCases, 1)); 

steps_constant_nsdevs_3                  = single(zeros(numberOfTestCases,1));
execution_time_constant_nsdevs_3         = single(zeros(numberOfTestCases,1));



%%
%batch testing begins here 
for fileIndex = 1 : numberOfTestCases
    
%% save function breakpoints while clearing
fileIndex;
save fileIndex

% Close all figures including those with hidden handles
close all hidden;

%Store all the currently set breakpoints in a variable
temporaryBreakpointData=dbstatus('-completenames');

% Clear functions and their persistent variables (also clears breakpoints
% set in functions)
clear functions;

% Restore the previously set breakpoints
dbstop(temporaryBreakpointData);

% Clear global variables
clear global;

% Clear variables (including the temporary one used to store breakpoints)
clear variables;
    
%% 

load fileIndex

if (fileIndex < 10)
    fileNameAndPath =...
    ['C:\Users\antonio\Dropbox\Tesis de Antonio Rueda\CIMENICS_2014\Test Datasets\BRATS_HG000'...
         num2str(fileIndex) '_truth_and_data.mat'];
    
else
    fileNameAndPath =...
    ['C:\Users\antonio\Dropbox\Tesis de Antonio Rueda\CIMENICS_2014\Test Datasets\BRATS_HG00'...
        num2str(fileIndex) '_truth_and_data.mat'];
   
end

load(fileNameAndPath);

%% prep for processing

channelOne   = single(t1   (:, :,:));
channelTwo   = single(t1Gad(:,:,:));
channelThree = single(t2   (:,:,:));
channelFour  = single(flair(:,:,:));

clearvars t1 t1Gad t2 flair 

%done to avoid numerical errors while using exponential penalty
channelOne   = channelOne    ./ 255;
channelTwo   = channelTwo    ./ 255;
channelThree = channelThree  ./ 255;
channelFour  = channelFour   ./ 255;

channels_norm2 = sqrt( channelOne   .^2  + channelTwo .^2  +...
                       channelThree .^2 + channelFour .^2 ); 

max_norm2 = single(max(channels_norm2(:)));

%init tuples info
xDim = size(channelOne,1);
yDim = size(channelOne,2);
zDim = size(channelOne,3);

strength = zeros(xDim, yDim, zDim);
label    = uint8(zeros(xDim, yDim, zDim));


%% load seeds
size_loaded_tumor_seeds              = floor(size(tumor_coordinates_in_volume,1)              * 0.05);
size_loaded_edema_seeds              = floor(size(edema_coordinates_in_volume,1)              * 0.05);
size_loaded_healthy_background_seeds = floor(size(healthy_background_coordinates_in_volume,1) * 0.05);
size_loaded_empty_background_seeds   = floor(size(empty_background_coordinates_in_volume,1)   * 0.05);

seg_label_for_tumor = 1;


for l_index = 1:size_loaded_tumor_seeds
    
    x = tumor_coordinates_in_volume(random_tumor_indices_in_volume(l_index),1);
    y = tumor_coordinates_in_volume(random_tumor_indices_in_volume(l_index),2);
    z = tumor_coordinates_in_volume(random_tumor_indices_in_volume(l_index),3);
    
    strength(x,y,z) = 1.0;
    label   (x,y,z) = seg_label_for_tumor;
    
    
end

seg_label_for_edema = 2;

for l_index = 1:size_loaded_edema_seeds
    
    x = edema_coordinates_in_volume(random_edema_indices_in_volume(l_index),1);
    y = edema_coordinates_in_volume(random_edema_indices_in_volume(l_index),2);
    z = edema_coordinates_in_volume(random_edema_indices_in_volume(l_index),3);
    
    strength(x,y,z) = 1.0;
    label   (x,y,z) = seg_label_for_edema;
    
    
end

seg_label_for_healthy_background = 3;

for l_index = 1:size_loaded_healthy_background_seeds
    
    x = healthy_background_coordinates_in_volume(random_healthy_background_indices_in_volume(l_index),1);
    y = healthy_background_coordinates_in_volume(random_healthy_background_indices_in_volume(l_index),2);
    z = healthy_background_coordinates_in_volume(random_healthy_background_indices_in_volume(l_index),3);
    
    strength(x,y,z) = 1.0;
    label   (x,y,z) = seg_label_for_healthy_background;
    
end

seg_label_for_empty_background = 4;

for l_index = 1:size_loaded_empty_background_seeds
    
    x = empty_background_coordinates_in_volume(random_empty_background_indices_in_volume(l_index),1);
    y = empty_background_coordinates_in_volume(random_empty_background_indices_in_volume(l_index),2);
    z = empty_background_coordinates_in_volume(random_empty_background_indices_in_volume(l_index),3);
    
    strength(x,y,z) = 1.0;
    label   (x,y,z) = seg_label_for_empty_background;
    
end

%% calculate means and sdevs of seeds in channels_norm2
nclas = 4;

means = zeros([nclas,1]);
sdevs = zeros([nclas,1]);

for class_index = 1 : nclas
    
    class_mask = (label == class_index);
    
    means(class_index) = mean(channels_norm2(class_mask));
    sdevs(class_index) = std (channels_norm2(class_mask));
    
end

%% label consistency between truth and segmentation
truth_label_for_tumor              = seg_label_for_tumor;
truth_label_for_edema              = seg_label_for_edema;
truth_label_for_healthy_background = seg_label_for_healthy_background;
truth_label_for_empty_background   = seg_label_for_empty_background;

%% call various versions of growcut

%% call original growcut
[segmentation_vezhnevets, strength_map_vezhnevets,...
 steps_vezhnevets(fileIndex), execution_time_vezhnevets(fileIndex)] =...
   ...
  call_cuda_growcut_vezhnevets_multichannel ( channelOne,   channelTwo,...
                                              channelThree, channelFour,...
                                              label, strength, max_norm2 );

% show segmentation and strength map                                              
figure('Name', 'Segmentation Result - Vezhnevets'),...
   imshow(segmentation_vezhnevets(:,:,tumor_slice),    'DisplayRange', []);

figure('name', 'Strength - Vezhnevets'),...
   imshow(strength_map_vezhnevets(:,:,tumor_slice),    'DisplayRange', []);

%% call corrected growcut
[segmentation_corrected, strength_map_corrected,...
 steps_corrected(fileIndex), execution_time_corrected(fileIndex)] =...
 ...
 call_cuda_growcut_corrected_multichannel ( channelOne, channelTwo,...
                                            channelThree,channelFour,...
                                            label, strength, max_norm2 );
                                        
% show segmentation and strength map  
figure('Name', 'Segmentation Result - corrected'),...
    imshow(segmentation_corrected(:,:,tumor_slice),    'DisplayRange', []);

figure('name', 'Strength - corrected'),...
    imshow(strength_map_corrected(:,:,tumor_slice),    'DisplayRange', []);

%% call exponential penalty growcut, nsdevs = 1

% penalize the strength of attacks coming from cells 1 sdev away from mean 
nsdevs = 1;

[segmentation_exponential_nsdevs_1,...
 strength_map_exponential_nsdevs_1,...
 steps_exponential_nsdevs_1(fileIndex),...
 execution_time_exponential_nsdevs_1(fileIndex)] =...
 ...
 call_cuda_growcut_exponential_penalty_multichannel (channelOne,...
                                                     channelTwo,...
                                                     channelThree,...
                                                     channelFour,...
                                                     label, strength,...
                                                     max_norm2,...
                                                     ...
                                                     means, sdevs,...
                                                     nsdevs);

% show segmentation and strength map  
figure('Name', 'Segmentation Result - exponential, nsdevs = 1'),...
    imshow(segmentation_exponential_nsdevs_1(:,:,tumor_slice), ....
           'DisplayRange', []);
       
figure('name', 'Strength - exponential, nsdevs = 1'),...
    imshow(strength_map_exponential_nsdevs_1(:,:,tumor_slice),...
           'DisplayRange', []);

%% call exponential penalty growcut, nsdevs = 2

% penalize the strength of attacks coming from cells 2 sdevs away from mean 
nsdevs = 2;

[segmentation_exponential_nsdevs_2,...
 strength_map_exponential_nsdevs_2,...
 steps_exponential_nsdevs_2(fileIndex),...
 execution_time_exponential_nsdevs_2(fileIndex)] =...
 ...
 call_cuda_growcut_exponential_penalty_multichannel (channelOne,...
                                                     channelTwo,...
                                                     channelThree,...
                                                     channelFour,...
                                                     label, strength,...
                                                     max_norm2,...
                                                     means, sdevs,...
                                                     nsdevs);

% show segmentation and strength map                                                 
figure('Name', 'Segmentation Result - exponential, nsdevs = 2'),...
   imshow(segmentation_exponential_nsdevs_2(:,:,tumor_slice),...
          'DisplayRange', []);

figure('name', 'Strength - exponential, nsdevs = 2'),...
   imshow(strength_map_exponential_nsdevs_2(:,:,tumor_slice),...
          'DisplayRange', []);

%% call exponential penalty growcut, nsdevs = 3

% penalize the strength of attacks coming from cells 3 sdevs away from mean
nsdevs = 3;

[segmentation_exponential_nsdevs_3,...
 strength_map_exponential_nsdevs_3,...
 steps_exponential_nsdevs_3(fileIndex),...
 execution_time_exponential_nsdevs_3(fileIndex)] =...
    ...
    call_cuda_growcut_exponential_penalty_multichannel (channelOne,...
                                                        channelTwo,...
                                                        channelThree,...
                                                        channelFour,...
                                                        label, strength,...
                                                        max_norm2,...
                                                        means, sdevs,...
                                                        nsdevs);
                                                    
% show segmentation and strength map                                    
figure('Name', 'Segmentation Result - exponential, nsdevs = 3'),...
    imshow(segmentation_exponential_nsdevs_3(:,:,tumor_slice),...
           'DisplayRange', []);
       
figure('name', 'Strength - exponential, nsdevs = 3'),...
    imshow(strength_map_exponential_nsdevs_3(:,:,tumor_slice),...
           'DisplayRange', []);


%% call linear penalty growcut, nsdevs = 1

% penalize the strength of attacks coming from cells 1 sdev away from mean
nsdevs = 1; 

[segmentation_linear_nsdevs_1, strength_map_linear_nsdevs_1,...
 steps_linear_nsdevs_1(fileIndex),...
 execution_time_linear_nsdevs_1(fileIndex)] =...
    ...
    call_cuda_growcut_linear_penalty_multichannel (channelOne,...
                                                   channelTwo,...
                                                   channelThree,...
                                                   channelFour,...
                                                   label, strength,...
                                                   max_norm2,...
                                                   means, sdevs, nsdevs);
% show segmentation and strength map   
figure('Name', 'Segmentation Result - linear penalty, nsdevs = 1 '),...
 imshow(segmentation_linear_nsdevs_1(:,:,tumor_slice),'DisplayRange', []);

figure('name', 'Strength - linear penalty, nsdevs = 1 '),...
 imshow(strength_map_linear_nsdevs_1(:,:,tumor_slice),'DisplayRange', []);

%% call linear penalty growcut, nsdevs = 2

% penalize the strength of attacks coming from cells 2 sdevs away from mean
nsdevs = 2; 

[segmentation_linear_nsdevs_2, strength_map_linear_nsdevs_2,...
 steps_linear_nsdevs_2(fileIndex),...
 execution_time_linear_nsdevs_2(fileIndex)] =...
 ...
 call_cuda_growcut_linear_penalty_multichannel (channelOne,...
                                                channelTwo,...
                                                channelThree,...
                                                channelFour,...
                                                label, strength,...
                                                max_norm2,...
                                                means, sdevs, nsdevs);

figure('Name', 'Segmentation Result - linear penalty, nsdevs = 2 '),...
 imshow(segmentation_linear_nsdevs_2(:,:,tumor_slice),'DisplayRange', []);

figure('name', 'Strength - linear penalty, nsdevs = 2 '),...
 imshow(strength_map_linear_nsdevs_2(:,:,tumor_slice),    'DisplayRange', []);

%% call linear penalty growcut, nsdevs = 3

% penalize the strength of attacks coming from cells 3 sdevs away from mean
nsdevs = 3;

[segmentation_linear_nsdevs_3, strength_map_linear_nsdevs_3,...
 steps_linear_nsdevs_3(fileIndex),...
 execution_time_linear_nsdevs_3(fileIndex)] =...
 ...
 call_cuda_growcut_linear_penalty_multichannel (channelOne, channelTwo,...
                                                channelThree, channelFour,...
                                                label, strength, max_norm2,...                                                        
                                                means, sdevs, nsdevs);

figure('Name', 'Segmentation Result - linear penalty, nsdevs = 3 '),...
 imshow(segmentation_linear_nsdevs_3(:,:,tumor_slice),'DisplayRange', []);

figure('name', 'Strength - linear penalty, nsdevs = 3 '),...
 imshow(strength_map_linear_nsdevs_3(:,:,tumor_slice),'DisplayRange', []);

%% call constant penalty growcut, nsdevs = 1

% penalize the strength of attacks coming from cells 2 sdevs away from mean

high_penalty = 0.95;
low_penalty  = 0.99;

nsdevs = 1;

[segmentation_constant_nsdevs_1, strength_map_constant_nsdevs_1,...
 steps_constant_nsdevs_1(fileIndex),...
 execution_time_constant_nsdevs_1(fileIndex)] =...
 ...
 call_cuda_growcut_constant_penalty_multichannel (channelOne,...
                                                  channelTwo,...
                                                  channelThree,...
                                                  channelFour,...
                                                  label, strength,...
                                                  max_norm2,...
                                                  means, sdevs, nsdevs,...
                                                  high_penalty,...
                                                  low_penalty...
                                                  );
                                              
figure('Name', 'Segmentation Result - constant penalty, nsdevs = 1 '),
 imshow(segmentation_constant_nsdevs_1(:,:,tumor_slice),'DisplayRange', []);
 
figure('name', 'Strength - constant penalty, nsdevs = 1 '),...
 imshow(strength_map_constant_nsdevs_1(:,:,tumor_slice),'DisplayRange', []);

%% call constant penalty growcut, nsdevs = 2

% penalize the strength of attacks coming from cells 2 sdevs away from mean

high_penalty = 0.95;
low_penalty  = 0.99;

nsdevs = 2;

[segmentation_constant_nsdevs_2, strength_map_constant_nsdevs_2,...
 steps_constant_nsdevs_2(fileIndex),...
 execution_time_constant_nsdevs_2(fileIndex)] =...
 ...
 call_cuda_growcut_constant_penalty_multichannel (channelOne,...
                                                  channelTwo,...
                                                  channelThree,...
                                                  channelFour,...
                                                  label, strength,...
                                                  max_norm2,...
                                                  means, sdevs, nsdevs,...
                                                  high_penalty,...
                                                  low_penalty...
                                                  );
                                              
figure('Name', 'Segmentation Result - constant penalty, nsdevs = 2 '),...
 imshow(segmentation_constant_nsdevs_2(:,:,tumor_slice),'DisplayRange', []);

figure('name', 'Strength - constant penalty, nsdevs = 2 '),...
 imshow(strength_map_constant_nsdevs_2(:,:,tumor_slice),'DisplayRange', []);

%% call constant penalty growcut, nsdevs = 3

% penalize the strength of attacks coming from cells 3 sdevs away from mean

high_penalty = 0.95;
low_penalty  = 0.99;

nsdevs = 3;

[segmentation_constant_nsdevs_3, strength_map_constant_nsdevs_3,...
 steps_constant_nsdevs_3(fileIndex),...
 execution_time_constant_nsdevs_3(fileIndex)] =...
 ...
 call_cuda_growcut_constant_penalty_multichannel ( channelOne,...
                                                   channelTwo,...
                                                   channelThree,...
                                                   channelFour,...
                                                   label, strength,...
                                                   max_norm2,...
                                                   means, sdevs, nsdevs,...
                                                   high_penalty,...
                                                   low_penalty...
                                                   );
                                               
figure('Name', 'Segmentation Result - constant penalty, nsdevs = 3 '),...
 imshow(segmentation_constant_nsdevs_3(:,:,tumor_slice),'DisplayRange', []);

figure('name', 'Strength - constant penalty, nsdevs = 3 '),...
 imshow(strength_map_constant_nsdevs_3(:,:,tumor_slice),'DisplayRange', []);



%% validate 

%validate vezhnevets's growcut

[         dice_coefficient_tumor_vezhnevets(fileIndex),...
               sensitivity_tumor_vezhnevets(fileIndex),...
                 precision_tumor_vezhnevets(fileIndex), ...
               specificity_tumor_vezhnevets(fileIndex),...
          ...
          ...
          dice_coefficient_edema_vezhnevets(fileIndex),...
               sensitivity_edema_vezhnevets(fileIndex),...
                 precision_edema_vezhnevets(fileIndex), ...
               specificity_edema_vezhnevets(fileIndex)...          
          ...
          ...
] ...
   = full_bounded_validation_function( segmentation_vezhnevets, truth,...
                                        seg_label_for_tumor,...
                                        seg_label_for_edema,...
                                        truth_label_for_tumor,...
                                        truth_label_for_edema);

%validate corrected growcut

[         dice_coefficient_tumor_corrected(fileIndex),...
               sensitivity_tumor_corrected(fileIndex),...
                 precision_tumor_corrected(fileIndex), ...
               specificity_tumor_corrected(fileIndex),...
          ...
          ...
          dice_coefficient_edema_corrected(fileIndex),...
               sensitivity_edema_corrected(fileIndex),...
                 precision_edema_corrected(fileIndex), ...
               specificity_edema_corrected(fileIndex)...          
          ...
          ...
] ...
    = full_bounded_validation_function( segmentation_corrected,...
                                        truth,...
                                        seg_label_for_tumor,...
                                        seg_label_for_edema,...
                                        truth_label_for_tumor,...
                                        truth_label_for_edema);
                                    
%validate growcut with exponential penalty, sdevs =1 

[         dice_coefficient_tumor_exponential_nsdevs_1(fileIndex),...
               sensitivity_tumor_exponential_nsdevs_1(fileIndex),...
                 precision_tumor_exponential_nsdevs_1(fileIndex), ...
               specificity_tumor_exponential_nsdevs_1(fileIndex),...
          ...
          ...
          dice_coefficient_edema_exponential_nsdevs_1(fileIndex),...
               sensitivity_edema_exponential_nsdevs_1(fileIndex),...
                 precision_edema_exponential_nsdevs_1(fileIndex), ...
               specificity_edema_exponential_nsdevs_1(fileIndex)...          
          ...
          ...
] ...
    = full_bounded_validation_function( segmentation_exponential_nsdevs_1,...
                                        truth,...
                                        seg_label_for_tumor,...
                                        seg_label_for_edema,...
                                        truth_label_for_tumor,...
                                        truth_label_for_edema);

%validate growcut with exponential penalty, sdevs =2

[         dice_coefficient_tumor_exponential_nsdevs_2(fileIndex),...
               sensitivity_tumor_exponential_nsdevs_2(fileIndex),...
                 precision_tumor_exponential_nsdevs_2(fileIndex), ...
               specificity_tumor_exponential_nsdevs_2(fileIndex),...
          ...
          ...
          dice_coefficient_edema_exponential_nsdevs_2(fileIndex),...
               sensitivity_edema_exponential_nsdevs_2(fileIndex),...
                 precision_edema_exponential_nsdevs_2(fileIndex), ...
               specificity_edema_exponential_nsdevs_2(fileIndex)...          
          ...
          ...
] ...
    = full_bounded_validation_function( segmentation_exponential_nsdevs_2,...
                                        truth,...
                                        seg_label_for_tumor,...
                                        seg_label_for_edema,...
                                        truth_label_for_tumor,...
                                        truth_label_for_edema);                                    
                                    
%validate growcut with exponential penalty, sdevs =3

[         dice_coefficient_tumor_exponential_nsdevs_3(fileIndex),...
               sensitivity_tumor_exponential_nsdevs_3(fileIndex),...
                 precision_tumor_exponential_nsdevs_3(fileIndex), ...
               specificity_tumor_exponential_nsdevs_3(fileIndex),...
          ...
          ...
          dice_coefficient_edema_exponential_nsdevs_3(fileIndex),...
               sensitivity_edema_exponential_nsdevs_3(fileIndex),...
                 precision_edema_exponential_nsdevs_3(fileIndex), ...
               specificity_edema_exponential_nsdevs_3(fileIndex)...          
          ...
          ...
] ...
    = full_bounded_validation_function( segmentation_exponential_nsdevs_3,...
                                        truth,...
                                        seg_label_for_tumor,...
                                        seg_label_for_edema,...
                                        truth_label_for_tumor,...
                                        truth_label_for_edema);                                       

% validate growcut with linear penalty, sdevs =1

[         dice_coefficient_tumor_linear_nsdevs_1(fileIndex),...
               sensitivity_tumor_linear_nsdevs_1(fileIndex),...
                 precision_tumor_linear_nsdevs_1(fileIndex), ...
               specificity_tumor_linear_nsdevs_1(fileIndex),...
          ...
          ...
          dice_coefficient_edema_linear_nsdevs_1(fileIndex),...
               sensitivity_edema_linear_nsdevs_1(fileIndex),...
                 precision_edema_linear_nsdevs_1(fileIndex), ...
               specificity_edema_linear_nsdevs_1(fileIndex)...          
          ...
          ...
] ...
    = full_bounded_validation_function( segmentation_linear_nsdevs_1,...
                                        truth,...
                                        seg_label_for_tumor,...
                                        seg_label_for_edema,...
                                        truth_label_for_tumor,...
                                        truth_label_for_edema);
                                    
% validate growcut with linear penalty, sdevs =2
[         dice_coefficient_tumor_linear_nsdevs_2(fileIndex),...
               sensitivity_tumor_linear_nsdevs_2(fileIndex),...
                 precision_tumor_linear_nsdevs_2(fileIndex), ...
               specificity_tumor_linear_nsdevs_2(fileIndex),...
          ...
          ...
          dice_coefficient_edema_linear_nsdevs_2(fileIndex),...
               sensitivity_edema_linear_nsdevs_2(fileIndex),...
                 precision_edema_linear_nsdevs_2(fileIndex), ...
               specificity_edema_linear_nsdevs_2(fileIndex)...          
          ...
          ...
] ...
    = full_bounded_validation_function( segmentation_linear_nsdevs_2,...
                                        truth,...
                                        seg_label_for_tumor,...
                                        seg_label_for_edema,...
                                        truth_label_for_tumor,...
                                        truth_label_for_edema);                                    
                                    
%validate growcut with linear penalty, sdevs =3

[         dice_coefficient_tumor_linear_nsdevs_3(fileIndex),...
               sensitivity_tumor_linear_nsdevs_3(fileIndex),...
                 precision_tumor_linear_nsdevs_3(fileIndex), ...
               specificity_tumor_linear_nsdevs_3(fileIndex),...
          ...
          ...
          dice_coefficient_edema_linear_nsdevs_3(fileIndex),...
               sensitivity_edema_linear_nsdevs_3(fileIndex),...
                 precision_edema_linear_nsdevs_3(fileIndex), ...
               specificity_edema_linear_nsdevs_3(fileIndex)...          
          ...
          ...
] ...
    = full_bounded_validation_function(segmentation_linear_nsdevs_3,...
                                       truth,...
                                       seg_label_for_tumor,...
                                       seg_label_for_edema,...
                                       truth_label_for_tumor,...
                                       truth_label_for_edema);                                       
                                 
                                   
%validate growcut with constant penalty, sdevs =1
[         dice_coefficient_tumor_constant_nsdevs_1(fileIndex),...
               sensitivity_tumor_constant_nsdevs_1(fileIndex),...
                 precision_tumor_constant_nsdevs_1(fileIndex), ...
               specificity_tumor_constant_nsdevs_1(fileIndex),...
          ...
          ...
          dice_coefficient_edema_constant_nsdevs_1(fileIndex),...
               sensitivity_edema_constant_nsdevs_1(fileIndex),...
                 precision_edema_constant_nsdevs_1(fileIndex), ...
               specificity_edema_constant_nsdevs_1(fileIndex)...          
          ...
          ...
] ...
    = full_bounded_validation_function( segmentation_constant_nsdevs_1,...
                                        truth,...
                                        seg_label_for_tumor,...
                                        seg_label_for_edema,...
                                        truth_label_for_tumor,...
                                        truth_label_for_edema);                                      
                                    
%validate growcut with constant penalty, sdevs =2
[         dice_coefficient_tumor_constant_nsdevs_2(fileIndex),...
               sensitivity_tumor_constant_nsdevs_2(fileIndex),...
                 precision_tumor_constant_nsdevs_2(fileIndex), ...
               specificity_tumor_constant_nsdevs_2(fileIndex),...
          ...
          ...
          dice_coefficient_edema_constant_nsdevs_2(fileIndex),...
               sensitivity_edema_constant_nsdevs_2(fileIndex),...
                 precision_edema_constant_nsdevs_2(fileIndex), ...
               specificity_edema_constant_nsdevs_2(fileIndex)...          
          ...
          ...
] ...
    = full_bounded_validation_function( segmentation_constant_nsdevs_2,...
                                        truth,...
                                        seg_label_for_tumor,...
                                        seg_label_for_edema,...
                                        truth_label_for_tumor,...
                                        truth_label_for_edema);                                    
                                    
%validate growcut with constant penalty, sdevs =3
[         dice_coefficient_tumor_constant_nsdevs_3(fileIndex),...
               sensitivity_tumor_constant_nsdevs_3(fileIndex),...
                 precision_tumor_constant_nsdevs_3(fileIndex), ...
               specificity_tumor_constant_nsdevs_3(fileIndex),...
          ...
          ...
          dice_coefficient_edema_constant_nsdevs_3(fileIndex),...
               sensitivity_edema_constant_nsdevs_3(fileIndex),...
                 precision_edema_constant_nsdevs_3(fileIndex),...
               specificity_edema_constant_nsdevs_3(fileIndex)...          
          ...
          ...
] ...
    = full_bounded_validation_function( segmentation_constant_nsdevs_3,...
                                        truth,...
                                        seg_label_for_tumor,...
                                        seg_label_for_edema,...
                                        truth_label_for_tumor,...
                                        truth_label_for_edema);                                                                         
%% save invididual results to file

if (fileIndex < 10)
ResultsPathAndName = ...
    ['D:\Dropbox\Tesis de Antonio Rueda\CIMENICS_2014\Results\BRATS_HG000'...
         num2str(fileIndex) '_4_channels_4_labels_Results.mat'];
else
ResultsPathAndName = ...
    ['D:\Dropbox\Tesis de Antonio Rueda\CIMENICS_2014\Results\BRATS_HG00'...
         num2str(fileIndex) '_4_channels_4_labels_Results.mat'];
    
end
     
%name conversion (added "_" ) done just for the sake of Matlab's save syntax     


steps_vezhnevets_                         = steps_vezhnevets(fileIndex);            
execution_time_vezhnevets_                = execution_time_vezhnevets(fileIndex); 
dice_coefficient_tumor_vezhnevets_        = dice_coefficient_tumor_vezhnevets(fileIndex);    
sensitivity_tumor_vezhnevets_             = sensitivity_tumor_vezhnevets(fileIndex);
precision_tumor_vezhnevets_               = precision_tumor_vezhnevets(fileIndex);  
specificity_tumor_vezhnevets_             = specificity_tumor_vezhnevets(fileIndex); 
dice_coefficient_edema_vezhnevets_        = dice_coefficient_edema_vezhnevets(fileIndex);    
sensitivity_edema_vezhnevets_             = sensitivity_edema_vezhnevets(fileIndex);
precision_edema_vezhnevets_               = precision_edema_vezhnevets(fileIndex);  
specificity_edema_vezhnevets_             = specificity_edema_vezhnevets(fileIndex); 
        

steps_corrected_                          = steps_corrected(fileIndex);              
execution_time_corrected_                 = execution_time_corrected(fileIndex);     
dice_coefficient_tumor_corrected_         = dice_coefficient_tumor_corrected(fileIndex);
sensitivity_tumor_corrected_              = sensitivity_tumor_corrected(fileIndex);  
precision_tumor_corrected_                = precision_tumor_corrected(fileIndex);   
specificity_tumor_corrected_              = specificity_tumor_corrected(fileIndex);  
dice_coefficient_edema_corrected_         = dice_coefficient_edema_corrected(fileIndex);
sensitivity_edema_corrected_              = sensitivity_edema_corrected(fileIndex);  
precision_edema_corrected_                = precision_edema_corrected(fileIndex);   
specificity_edema_corrected_              = specificity_edema_corrected(fileIndex);   
     

steps_exponential_nsdevs_1_                        = steps_exponential_nsdevs_1(fileIndex);              
execution_time_exponential_nsdevs_1_               = execution_time_exponential_nsdevs_1(fileIndex);     
dice_coefficient_tumor_exponential_nsdevs_1_       = dice_coefficient_tumor_exponential_nsdevs_1(fileIndex);
sensitivity_tumor_exponential_nsdevs_1_            = sensitivity_tumor_exponential_nsdevs_1(fileIndex);  
precision_tumor_exponential_nsdevs_1_              = precision_tumor_exponential_nsdevs_1(fileIndex);   
specificity_tumor_exponential_nsdevs_1_            = specificity_tumor_exponential_nsdevs_1(fileIndex);  
dice_coefficient_edema_exponential_nsdevs_1_       = dice_coefficient_edema_exponential_nsdevs_1(fileIndex);
sensitivity_edema_exponential_nsdevs_1_            = sensitivity_edema_exponential_nsdevs_1(fileIndex);  
precision_edema_exponential_nsdevs_1_              = precision_edema_exponential_nsdevs_1(fileIndex);   
specificity_edema_exponential_nsdevs_1_            = specificity_edema_exponential_nsdevs_1(fileIndex); 


steps_exponential_nsdevs_2_                        = steps_exponential_nsdevs_2(fileIndex);              
execution_time_exponential_nsdevs_2_               = execution_time_exponential_nsdevs_2(fileIndex);     
dice_coefficient_tumor_exponential_nsdevs_2_       = dice_coefficient_tumor_exponential_nsdevs_2(fileIndex);
sensitivity_tumor_exponential_nsdevs_2_            = sensitivity_tumor_exponential_nsdevs_2(fileIndex);  
precision_tumor_exponential_nsdevs_2_              = precision_tumor_exponential_nsdevs_2(fileIndex);   
specificity_tumor_exponential_nsdevs_2_            = specificity_tumor_exponential_nsdevs_2(fileIndex);  
dice_coefficient_edema_exponential_nsdevs_2_       = dice_coefficient_edema_exponential_nsdevs_2(fileIndex);
sensitivity_edema_exponential_nsdevs_2_            = sensitivity_edema_exponential_nsdevs_2(fileIndex);  
precision_edema_exponential_nsdevs_2_              = precision_edema_exponential_nsdevs_2(fileIndex);   
specificity_edema_exponential_nsdevs_2_            = specificity_edema_exponential_nsdevs_2(fileIndex);


steps_exponential_nsdevs_3_                        = steps_exponential_nsdevs_3(fileIndex);              
execution_time_exponential_nsdevs_3_               = execution_time_exponential_nsdevs_3(fileIndex);     
dice_coefficient_tumor_exponential_nsdevs_3_       = dice_coefficient_tumor_exponential_nsdevs_3(fileIndex);
sensitivity_tumor_exponential_nsdevs_3_            = sensitivity_tumor_exponential_nsdevs_3(fileIndex);  
precision_tumor_exponential_nsdevs_3_              = precision_tumor_exponential_nsdevs_3(fileIndex);   
specificity_tumor_exponential_nsdevs_3_            = specificity_tumor_exponential_nsdevs_3(fileIndex);  
dice_coefficient_edema_exponential_nsdevs_3_       = dice_coefficient_edema_exponential_nsdevs_3(fileIndex);
sensitivity_edema_exponential_nsdevs_3_            = sensitivity_edema_exponential_nsdevs_3(fileIndex);  
precision_edema_exponential_nsdevs_3_              = precision_edema_exponential_nsdevs_3(fileIndex);   
specificity_edema_exponential_nsdevs_3_            = specificity_edema_exponential_nsdevs_3(fileIndex); 


steps_linear_nsdevs_1_                             = steps_linear_nsdevs_1(fileIndex);              
execution_time_linear_nsdevs_1_                    = execution_time_linear_nsdevs_1(fileIndex);     
dice_coefficient_tumor_linear_nsdevs_1_            = dice_coefficient_tumor_linear_nsdevs_1(fileIndex);
sensitivity_tumor_linear_nsdevs_1_                 = sensitivity_tumor_linear_nsdevs_1(fileIndex);  
precision_tumor_linear_nsdevs_1_                   = precision_tumor_linear_nsdevs_1(fileIndex);   
specificity_tumor_linear_nsdevs_1_                 = specificity_tumor_linear_nsdevs_1(fileIndex);  
dice_coefficient_edema_linear_nsdevs_1_            = dice_coefficient_edema_linear_nsdevs_1(fileIndex);
sensitivity_edema_linear_nsdevs_1_                 = sensitivity_edema_linear_nsdevs_1(fileIndex);  
precision_edema_linear_nsdevs_1_                   = precision_edema_linear_nsdevs_1(fileIndex);   
specificity_edema_linear_nsdevs_1_                 = specificity_edema_linear_nsdevs_1(fileIndex);


steps_linear_nsdevs_2_                             = steps_linear_nsdevs_2(fileIndex);              
execution_time_linear_nsdevs_2_                    = execution_time_linear_nsdevs_2(fileIndex);     
dice_coefficient_tumor_linear_nsdevs_2_            = dice_coefficient_tumor_linear_nsdevs_2(fileIndex);
sensitivity_tumor_linear_nsdevs_2_                 = sensitivity_tumor_linear_nsdevs_2(fileIndex);  
precision_tumor_linear_nsdevs_2_                   = precision_tumor_linear_nsdevs_2(fileIndex);   
specificity_tumor_linear_nsdevs_2_                 = specificity_tumor_linear_nsdevs_2(fileIndex);  
dice_coefficient_edema_linear_nsdevs_2_            = dice_coefficient_edema_linear_nsdevs_2(fileIndex);
sensitivity_edema_linear_nsdevs_2_                 = sensitivity_edema_linear_nsdevs_2(fileIndex);  
precision_edema_linear_nsdevs_2_                   = precision_edema_linear_nsdevs_2(fileIndex);   
specificity_edema_linear_nsdevs_2_                 = specificity_edema_linear_nsdevs_2(fileIndex); 

steps_linear_nsdevs_3_                             = steps_linear_nsdevs_3(fileIndex);              
execution_time_linear_nsdevs_3_                    = execution_time_linear_nsdevs_3(fileIndex);     
dice_coefficient_tumor_linear_nsdevs_3_            = dice_coefficient_tumor_linear_nsdevs_3(fileIndex);
sensitivity_tumor_linear_nsdevs_3_                 = sensitivity_tumor_linear_nsdevs_3(fileIndex);  
precision_tumor_linear_nsdevs_3_                   = precision_tumor_linear_nsdevs_3(fileIndex);   
specificity_tumor_linear_nsdevs_3_                 = specificity_tumor_linear_nsdevs_3(fileIndex);  
dice_coefficient_edema_linear_nsdevs_3_            = dice_coefficient_edema_linear_nsdevs_3(fileIndex);
sensitivity_edema_linear_nsdevs_3_                 = sensitivity_edema_linear_nsdevs_3(fileIndex);  
precision_edema_linear_nsdevs_3_                   = precision_edema_linear_nsdevs_3(fileIndex);   
specificity_edema_linear_nsdevs_3_                 = specificity_edema_linear_nsdevs_3(fileIndex); 


steps_constant_nsdevs_1_                           = steps_constant_nsdevs_1(fileIndex);              
execution_time_constant_nsdevs_1_                  = execution_time_constant_nsdevs_1(fileIndex);     
dice_coefficient_tumor_constant_nsdevs_1_          = dice_coefficient_tumor_constant_nsdevs_1(fileIndex);
sensitivity_tumor_constant_nsdevs_1_               = sensitivity_tumor_constant_nsdevs_1(fileIndex);  
precision_tumor_constant_nsdevs_1_                 = precision_tumor_constant_nsdevs_1(fileIndex);   
specificity_tumor_constant_nsdevs_1_               = specificity_tumor_constant_nsdevs_1(fileIndex);  
dice_coefficient_edema_constant_nsdevs_1_          = dice_coefficient_edema_constant_nsdevs_1(fileIndex);
sensitivity_edema_constant_nsdevs_1_               = sensitivity_edema_constant_nsdevs_1(fileIndex);  
precision_edema_constant_nsdevs_1_                 = precision_edema_constant_nsdevs_1(fileIndex);   
specificity_edema_constant_nsdevs_1_               = specificity_edema_constant_nsdevs_1(fileIndex); 


steps_constant_nsdevs_2_                           = steps_constant_nsdevs_2(fileIndex);              
execution_time_constant_nsdevs_2_                  = execution_time_constant_nsdevs_2(fileIndex);     
dice_coefficient_tumor_constant_nsdevs_2_          = dice_coefficient_tumor_constant_nsdevs_2(fileIndex);
sensitivity_tumor_constant_nsdevs_2_               = sensitivity_tumor_constant_nsdevs_2(fileIndex);  
precision_tumor_constant_nsdevs_2_                 = precision_tumor_constant_nsdevs_2(fileIndex);   
specificity_tumor_constant_nsdevs_2_               = specificity_tumor_constant_nsdevs_2(fileIndex);  
dice_coefficient_edema_constant_nsdevs_2_          = dice_coefficient_edema_constant_nsdevs_2(fileIndex);
sensitivity_edema_constant_nsdevs_2_               = sensitivity_edema_constant_nsdevs_2(fileIndex);  
precision_edema_constant_nsdevs_2_                 = precision_edema_constant_nsdevs_2(fileIndex);   
specificity_edema_constant_nsdevs_2_               = specificity_edema_constant_nsdevs_2(fileIndex);


steps_constant_nsdevs_3_                           = steps_constant_nsdevs_3(fileIndex);              
execution_time_constant_nsdevs_3_                  = execution_time_constant_nsdevs_3(fileIndex);     
dice_coefficient_tumor_constant_nsdevs_3_          = dice_coefficient_tumor_constant_nsdevs_3(fileIndex);
sensitivity_tumor_constant_nsdevs_3_               = sensitivity_tumor_constant_nsdevs_3(fileIndex);  
precision_tumor_constant_nsdevs_3_                 = precision_tumor_constant_nsdevs_3(fileIndex);   
specificity_tumor_constant_nsdevs_3_               = specificity_tumor_constant_nsdevs_3(fileIndex);  
dice_coefficient_edema_constant_nsdevs_3_          = dice_coefficient_edema_constant_nsdevs_3(fileIndex);
sensitivity_edema_constant_nsdevs_3_               = sensitivity_edema_constant_nsdevs_3(fileIndex);  
precision_edema_constant_nsdevs_3_                 = precision_edema_constant_nsdevs_3(fileIndex);   
specificity_edema_constant_nsdevs_3_               = specificity_edema_constant_nsdevs_3(fileIndex);
     
%%     
save(ResultsPathAndName, 'segmentation_vezhnevets',...
                         'steps_vezhnevets_',... 
                         'execution_time_vezhnevets_',...
                         'dice_coefficient_tumor_vezhnevets_',...
                         'sensitivity_tumor_vezhnevets_',...
                         'precision_tumor_vezhnevets_', ...
                         'specificity_tumor_vezhnevets_',...
                         'dice_coefficient_edema_vezhnevets_',...
                         'sensitivity_edema_vezhnevets_',...
                         'precision_edema_vezhnevets_', ...
                         'specificity_edema_vezhnevets_',...
                         ...
                         'segmentation_corrected',...
                         'steps_corrected_',...
                         'execution_time_corrected_',...
                         'dice_coefficient_tumor_corrected_',...
                         'sensitivity_tumor_corrected_',...
                         'precision_tumor_corrected_', ...
                         'specificity_tumor_corrected_',...
                         'dice_coefficient_edema_corrected_',...
                         'sensitivity_edema_corrected_',...
                         'precision_edema_corrected_', ...
                         'specificity_edema_corrected_',...
                         ...
                         'segmentation_exponential_nsdevs_1',...
                         'steps_exponential_nsdevs_1_',...
                         'execution_time_exponential_nsdevs_1_',...
                         'dice_coefficient_tumor_exponential_nsdevs_1_',...
                         'sensitivity_tumor_exponential_nsdevs_1_',...
                         'precision_tumor_exponential_nsdevs_1_', ...
                         'specificity_tumor_exponential_nsdevs_1_',...
                         'dice_coefficient_edema_exponential_nsdevs_1_',...
                         'sensitivity_edema_exponential_nsdevs_1_',...
                         'precision_edema_exponential_nsdevs_1_', ...
                         'specificity_edema_exponential_nsdevs_1_',...
                         ...
                         'segmentation_exponential_nsdevs_2',...
                         'steps_exponential_nsdevs_2_',...
                         'execution_time_exponential_nsdevs_2_',...
                         'dice_coefficient_tumor_exponential_nsdevs_2_',...
                         'sensitivity_tumor_exponential_nsdevs_2_',...
                         'precision_tumor_exponential_nsdevs_2_', ...
                         'specificity_tumor_exponential_nsdevs_2_',...
                         'dice_coefficient_edema_exponential_nsdevs_2_',...
                         'sensitivity_edema_exponential_nsdevs_2_',...
                         'precision_edema_exponential_nsdevs_2_', ...
                         'specificity_edema_exponential_nsdevs_2_',...
                         ...
                         'segmentation_exponential_nsdevs_3',...
                         'steps_exponential_nsdevs_3_',...
                         'execution_time_exponential_nsdevs_3_',...
                         'dice_coefficient_tumor_exponential_nsdevs_3_',...
                         'sensitivity_tumor_exponential_nsdevs_3_',...
                         'precision_tumor_exponential_nsdevs_3_', ...
                         'specificity_tumor_exponential_nsdevs_3_',...
                         'dice_coefficient_edema_exponential_nsdevs_3_',...
                         'sensitivity_edema_exponential_nsdevs_3_',...
                         'precision_edema_exponential_nsdevs_3_', ...
                         'specificity_edema_exponential_nsdevs_3_',...
                         ...
                         'segmentation_linear_nsdevs_1',...
                         'steps_linear_nsdevs_1_',...
                         'execution_time_linear_nsdevs_1_',...
                         'dice_coefficient_tumor_linear_nsdevs_1_',...
                         'sensitivity_tumor_linear_nsdevs_1_',...
                         'precision_tumor_linear_nsdevs_1_', ...
                         'specificity_tumor_linear_nsdevs_1_',...
                         'dice_coefficient_edema_linear_nsdevs_1_',...
                         'sensitivity_edema_linear_nsdevs_1_',...
                         'precision_edema_linear_nsdevs_1_', ...
                         'specificity_edema_linear_nsdevs_1_',...
                         ...
                         'segmentation_linear_nsdevs_2',...
                         'steps_linear_nsdevs_2_',...
                         'execution_time_linear_nsdevs_2_',...
                         'dice_coefficient_tumor_linear_nsdevs_2_',...
                         'sensitivity_tumor_linear_nsdevs_2_',...
                         'precision_tumor_linear_nsdevs_2_', ...
                         'specificity_tumor_linear_nsdevs_2_',...
                         'dice_coefficient_edema_linear_nsdevs_2_',...
                         'sensitivity_edema_linear_nsdevs_2_',...
                         'precision_edema_linear_nsdevs_2_', ...
                         'specificity_edema_linear_nsdevs_2_',...
                         ...
                         'segmentation_linear_nsdevs_3',...
                         'steps_linear_nsdevs_3_',...
                         'execution_time_linear_nsdevs_3_',...
                         'dice_coefficient_tumor_linear_nsdevs_3_',...
                         'sensitivity_tumor_linear_nsdevs_3_',...
                         'precision_tumor_linear_nsdevs_3_', ...
                         'specificity_tumor_linear_nsdevs_3_',...
                         'dice_coefficient_edema_linear_nsdevs_3_',...
                         'sensitivity_edema_linear_nsdevs_3_',...
                         'precision_edema_linear_nsdevs_3_', ...
                         'specificity_edema_linear_nsdevs_3_',...                                 
                         ...
                         'segmentation_constant_nsdevs_1',...
                         'steps_constant_nsdevs_1_',...
                         'execution_time_constant_nsdevs_1_',...
                         'dice_coefficient_tumor_constant_nsdevs_1_',...
                         'sensitivity_tumor_constant_nsdevs_1_',...
                         'precision_tumor_constant_nsdevs_1_', ...
                         'specificity_tumor_constant_nsdevs_1_',...
                         'dice_coefficient_edema_constant_nsdevs_1_',...
                         'sensitivity_edema_constant_nsdevs_1_',...
                         'precision_edema_constant_nsdevs_1_', ...
                         'specificity_edema_constant_nsdevs_1_',...
                         ...
                         'segmentation_constant_nsdevs_2',...
                         'steps_constant_nsdevs_2_',...
                         'execution_time_constant_nsdevs_2_',...
                         'dice_coefficient_tumor_constant_nsdevs_2_',...
                         'sensitivity_tumor_constant_nsdevs_2_',...
                         'precision_tumor_constant_nsdevs_2_', ...
                         'specificity_tumor_constant_nsdevs_2_',...
                         'dice_coefficient_edema_constant_nsdevs_2_',...
                         'sensitivity_edema_constant_nsdevs_2_',...
                         'precision_edema_constant_nsdevs_2_', ...
                         'specificity_edema_constant_nsdevs_2_',...
                         ...
                         'segmentation_constant_nsdevs_3',...
                         'steps_constant_nsdevs_3_',...
                         'execution_time_constant_nsdevs_3_',...
                         'dice_coefficient_tumor_constant_nsdevs_3_',...
                         'sensitivity_tumor_constant_nsdevs_3_',...
                         'precision_tumor_constant_nsdevs_3_', ...
                         'specificity_tumor_constant_nsdevs_3_',...
                         'dice_coefficient_edema_constant_nsdevs_3_',...
                         'sensitivity_edema_constant_nsdevs_3_',...
                         'precision_edema_constant_nsdevs_3_', ...
                         'specificity_edema_constant_nsdevs_3_'...     
);

                     
end

mean_dice_coefficient_tumor_vezhnevets = mean(dice_coefficient_tumor_vezhnevets);
mean_sensitivity_tumor_vezhnevets      = mean(sensitivity_tumor_vezhnevets     );
mean_precision_tumor_vezhnevets        = mean(precision_tumor_vezhnevets       );
mean_specificity_tumor_vezhnevets      = mean(specificity_tumor_vezhnevets      );   
mean_dice_coefficient_edema_vezhnevets = mean(dice_coefficient_edema_vezhnevets);
mean_sensitivity_edema_vezhnevets      = mean(sensitivity_edema_vezhnevets     );
mean_precision_edema_vezhnevets        = mean(precision_edema_vezhnevets       );
mean_specificity_edema_vezhnevets      = mean(specificity_edema_vezhnevets     );
mean_steps_vezhnevets                  = mean(steps_vezhnevets                 );
mean_execution_time_vezhnevets         = mean(execution_time_vezhnevets        );

%%
mean_dice_coefficient_tumor_corrected = mean(dice_coefficient_tumor_corrected);
mean_sensitivity_tumor_corrected      = mean(sensitivity_tumor_corrected     );
mean_precision_tumor_corrected        = mean(precision_tumor_corrected       );
mean_specificity_tumor_corrected      = mean(specificity_tumor_corrected     );   
mean_dice_coefficient_edema_corrected = mean(dice_coefficient_edema_corrected);
mean_sensitivity_edema_corrected      = mean(sensitivity_edema_corrected     );
mean_precision_edema_corrected        = mean(precision_edema_corrected       );
mean_specificity_edema_corrected      = mean(specificity_edema_corrected     );
mean_steps_corrected                  = mean(steps_corrected                 );
mean_execution_time_corrected         = mean(execution_time_corrected        );

%%
mean_dice_coefficient_tumor_exponential_nsdevs_1 = mean(dice_coefficient_tumor_exponential_nsdevs_1);
mean_sensitivity_tumor_exponential_nsdevs_1      = mean(sensitivity_tumor_exponential_nsdevs_1     );
mean_precision_tumor_exponential_nsdevs_1        = mean(precision_tumor_exponential_nsdevs_1       );
mean_specificity_tumor_exponential_nsdevs_1      = mean(specificity_tumor_exponential_nsdevs_1     );   
mean_dice_coefficient_edema_exponential_nsdevs_1 = mean(dice_coefficient_edema_exponential_nsdevs_1);
mean_sensitivity_edema_exponential_nsdevs_1      = mean(sensitivity_edema_exponential_nsdevs_1     );
mean_precision_edema_exponential_nsdevs_1        = mean(precision_edema_exponential_nsdevs_1       );
mean_specificity_edema_exponential_nsdevs_1      = mean(specificity_edema_exponential_nsdevs_1     );
mean_steps_exponential_nsdevs_1                  = mean(steps_exponential_nsdevs_1                 );
mean_execution_time_exponential_nsdevs_1         = mean(execution_time_exponential_nsdevs_1        );

%%
mean_dice_coefficient_tumor_exponential_nsdevs_2 = mean(dice_coefficient_tumor_exponential_nsdevs_2);
mean_sensitivity_tumor_exponential_nsdevs_2      = mean(sensitivity_tumor_exponential_nsdevs_2     );
mean_precision_tumor_exponential_nsdevs_2        = mean(precision_tumor_exponential_nsdevs_2       );
mean_specificity_tumor_exponential_nsdevs_2      = mean(specificity_tumor_exponential_nsdevs_2     );   
mean_dice_coefficient_edema_exponential_nsdevs_2 = mean(dice_coefficient_edema_exponential_nsdevs_2);
mean_sensitivity_edema_exponential_nsdevs_2      = mean(sensitivity_edema_exponential_nsdevs_2     );
mean_precision_edema_exponential_nsdevs_2        = mean(precision_edema_exponential_nsdevs_2       );
mean_specificity_edema_exponential_nsdevs_2      = mean(specificity_edema_exponential_nsdevs_2     );
mean_steps_exponential_nsdevs_2                  = mean(steps_exponential_nsdevs_2                 );
mean_execution_time_exponential_nsdevs_2         = mean(execution_time_exponential_nsdevs_2        );

%%
mean_dice_coefficient_tumor_exponential_nsdevs_3 = mean(dice_coefficient_tumor_exponential_nsdevs_3);
mean_sensitivity_tumor_exponential_nsdevs_3      = mean(sensitivity_tumor_exponential_nsdevs_3     );
mean_precision_tumor_exponential_nsdevs_3        = mean(precision_tumor_exponential_nsdevs_3       );
mean_specificity_tumor_exponential_nsdevs_3      = mean(specificity_tumor_exponential_nsdevs_3     );   
mean_dice_coefficient_edema_exponential_nsdevs_3 = mean(dice_coefficient_edema_exponential_nsdevs_3);
mean_sensitivity_edema_exponential_nsdevs_3      = mean(sensitivity_edema_exponential_nsdevs_3     );
mean_precision_edema_exponential_nsdevs_3        = mean(precision_edema_exponential_nsdevs_3       );
mean_specificity_edema_exponential_nsdevs_3      = mean(specificity_edema_exponential_nsdevs_3     );
mean_steps_exponential_nsdevs_3                  = mean(steps_exponential_nsdevs_3                 );
mean_execution_time_exponential_nsdevs_3         = mean(execution_time_exponential_nsdevs_3        );


%%
mean_dice_coefficient_tumor_linear_nsdevs_1 = mean(dice_coefficient_tumor_linear_nsdevs_1);
mean_sensitivity_tumor_linear_nsdevs_1      = mean(sensitivity_tumor_linear_nsdevs_1     );
mean_precision_tumor_linear_nsdevs_1        = mean(precision_tumor_linear_nsdevs_1       );
mean_specificity_tumor_linear_nsdevs_1      = mean(specificity_tumor_linear_nsdevs_1     );   
mean_dice_coefficient_edema_linear_nsdevs_1 = mean(dice_coefficient_edema_linear_nsdevs_1);
mean_sensitivity_edema_linear_nsdevs_1      = mean(sensitivity_edema_linear_nsdevs_1     );
mean_precision_edema_linear_nsdevs_1        = mean(precision_edema_linear_nsdevs_1       );
mean_specificity_edema_linear_nsdevs_1      = mean(specificity_edema_linear_nsdevs_1     );
mean_steps_linear_nsdevs_1                  = mean(steps_linear_nsdevs_1                 );
mean_execution_time_linear_nsdevs_1         = mean(execution_time_linear_nsdevs_1        );

%%
mean_dice_coefficient_tumor_linear_nsdevs_2 = mean(dice_coefficient_tumor_linear_nsdevs_2);
mean_sensitivity_tumor_linear_nsdevs_2      = mean(sensitivity_tumor_linear_nsdevs_2     );
mean_precision_tumor_linear_nsdevs_2        = mean(precision_tumor_linear_nsdevs_2       );
mean_specificity_tumor_linear_nsdevs_2      = mean(specificity_tumor_linear_nsdevs_2     );   
mean_dice_coefficient_edema_linear_nsdevs_2 = mean(dice_coefficient_edema_linear_nsdevs_2);
mean_sensitivity_edema_linear_nsdevs_2      = mean(sensitivity_edema_linear_nsdevs_2     );
mean_precision_edema_linear_nsdevs_2        = mean(precision_edema_linear_nsdevs_2       );
mean_specificity_edema_linear_nsdevs_2      = mean(specificity_edema_linear_nsdevs_2     );
mean_steps_linear_nsdevs_2                  = mean(steps_linear_nsdevs_2                 );
mean_execution_time_linear_nsdevs_2         = mean(execution_time_linear_nsdevs_2        );

%%
mean_dice_coefficient_tumor_linear_nsdevs_3 = mean(dice_coefficient_tumor_linear_nsdevs_3);
mean_sensitivity_tumor_linear_nsdevs_3      = mean(sensitivity_tumor_linear_nsdevs_3     );
mean_precision_tumor_linear_nsdevs_3        = mean(precision_tumor_linear_nsdevs_3       );
mean_specificity_tumor_linear_nsdevs_3      = mean(specificity_tumor_linear_nsdevs_3     );   
mean_dice_coefficient_edema_linear_nsdevs_3 = mean(dice_coefficient_edema_linear_nsdevs_3);
mean_sensitivity_edema_linear_nsdevs_3      = mean(sensitivity_edema_linear_nsdevs_3     );
mean_precision_edema_linear_nsdevs_3        = mean(precision_edema_linear_nsdevs_3       );
mean_specificity_edema_linear_nsdevs_3      = mean(specificity_edema_linear_nsdevs_3     );
mean_steps_linear_nsdevs_3                  = mean(steps_linear_nsdevs_3                 );
mean_execution_time_linear_nsdevs_3         = mean(execution_time_linear_nsdevs_3        );

%%
mean_dice_coefficient_tumor_constant_nsdevs_1 = mean(dice_coefficient_tumor_constant_nsdevs_1);
mean_sensitivity_tumor_constant_nsdevs_1      = mean(sensitivity_tumor_constant_nsdevs_1     );
mean_precision_tumor_constant_nsdevs_1        = mean(precision_tumor_constant_nsdevs_1       );
mean_specificity_tumor_constant_nsdevs_1      = mean(specificity_tumor_constant_nsdevs_1     );   
mean_dice_coefficient_edema_constant_nsdevs_1 = mean(dice_coefficient_edema_constant_nsdevs_1);
mean_sensitivity_edema_constant_nsdevs_1      = mean(sensitivity_edema_constant_nsdevs_1     );
mean_precision_edema_constant_nsdevs_1        = mean(precision_edema_constant_nsdevs_1       );
mean_specificity_edema_constant_nsdevs_1      = mean(specificity_edema_constant_nsdevs_1     );
mean_steps_constant_nsdevs_1                  = mean(steps_constant_nsdevs_1                 );
mean_execution_time_constant_nsdevs_1         = mean(execution_time_constant_nsdevs_1        );

%%
mean_dice_coefficient_tumor_constant_nsdevs_2 = mean(dice_coefficient_tumor_constant_nsdevs_2);
mean_sensitivity_tumor_constant_nsdevs_2      = mean(sensitivity_tumor_constant_nsdevs_2     );
mean_precision_tumor_constant_nsdevs_2        = mean(precision_tumor_constant_nsdevs_2       );
mean_specificity_tumor_constant_nsdevs_2      = mean(specificity_tumor_constant_nsdevs_2     );   
mean_dice_coefficient_edema_constant_nsdevs_2 = mean(dice_coefficient_edema_constant_nsdevs_2);
mean_sensitivity_edema_constant_nsdevs_2      = mean(sensitivity_edema_constant_nsdevs_2     );
mean_precision_edema_constant_nsdevs_2        = mean(precision_edema_constant_nsdevs_2       );
mean_specificity_edema_constant_nsdevs_2      = mean(specificity_edema_constant_nsdevs_2     );
mean_steps_constant_nsdevs_2                  = mean(steps_constant_nsdevs_2                 );
mean_execution_time_constant_nsdevs_2         = mean(execution_time_constant_nsdevs_2        );

%%
mean_dice_coefficient_tumor_constant_nsdevs_3 = mean(dice_coefficient_tumor_constant_nsdevs_3);
mean_sensitivity_tumor_constant_nsdevs_3      = mean(sensitivity_tumor_constant_nsdevs_3     );
mean_precision_tumor_constant_nsdevs_3        = mean(precision_tumor_constant_nsdevs_3       );
mean_specificity_tumor_constant_nsdevs_3      = mean(specificity_tumor_constant_nsdevs_3     );   
mean_dice_coefficient_edema_constant_nsdevs_3 = mean(dice_coefficient_edema_constant_nsdevs_3);
mean_sensitivity_edema_constant_nsdevs_3      = mean(sensitivity_edema_constant_nsdevs_3     );
mean_precision_edema_constant_nsdevs_3        = mean(precision_edema_constant_nsdevs_3       );
mean_specificity_edema_constant_nsdevs_3      = mean(specificity_edema_constant_nsdevs_3     );
mean_steps_constant_nsdevs_3                  = mean(steps_constant_nsdevs_3                 );
mean_execution_time_constant_nsdevs_3         = mean(execution_time_constant_nsdevs_3        );

ResultsSummaryPathAndName = ...
    ['D:\Dropbox\Tesis de Antonio Rueda\CIMENICS_2014\Results\BRATS_HG_'...
         num2str(numberOfTestCases) '_testcases_4_channels_4_labels_ResultsSummary.mat'];

save (ResultsSummaryPathAndName,...
      ...
      'dice_coefficient_tumor_vezhnevets',...
      'sensitivity_tumor_vezhnevets',...
      'precision_tumor_vezhnevets',...
      'specificity_tumor_vezhnevets',...
      'dice_coefficient_edema_vezhnevets',...
      'sensitivity_edema_vezhnevets',...
      'precision_edema_vezhnevets',...
      'specificity_edema_vezhnevets',...
      'steps_vezhnevets',...
      'execution_time_vezhnevets',...
      ...
      'mean_dice_coefficient_tumor_vezhnevets',...
      'mean_sensitivity_tumor_vezhnevets',...
      'mean_precision_tumor_vezhnevets',...
      'mean_specificity_tumor_vezhnevets',...
      'mean_dice_coefficient_edema_vezhnevets',...
      'mean_sensitivity_edema_vezhnevets',...
      'mean_precision_edema_vezhnevets',...
      'mean_specificity_edema_vezhnevets',...
      'mean_steps_vezhnevets',...
      'mean_execution_time_vezhnevets',...
      ...
      'dice_coefficient_tumor_corrected',...
      'sensitivity_tumor_corrected',...
      'precision_tumor_corrected',...
      'specificity_tumor_corrected',...
      'dice_coefficient_edema_corrected',...
      'sensitivity_edema_corrected',...
      'precision_edema_corrected',...
      'specificity_edema_corrected',...
      'steps_corrected',...
      'execution_time_corrected',...
      ...
      'mean_dice_coefficient_tumor_corrected',...
      'mean_sensitivity_tumor_corrected',...
      'mean_precision_tumor_corrected',...
      'mean_specificity_tumor_corrected',...
      'mean_dice_coefficient_edema_corrected',...
      'mean_sensitivity_edema_corrected',...
      'mean_precision_edema_corrected',...
      'mean_specificity_edema_corrected',...
      'mean_steps_corrected',...
      'mean_execution_time_corrected',...
      ...
      'dice_coefficient_tumor_exponential_nsdevs_1',...
      'sensitivity_tumor_exponential_nsdevs_1',...
      'precision_tumor_exponential_nsdevs_1',...
      'specificity_tumor_exponential_nsdevs_1',...
      'dice_coefficient_edema_exponential_nsdevs_1',...
      'sensitivity_edema_exponential_nsdevs_1',...
      'precision_edema_exponential_nsdevs_1',...
      'specificity_edema_exponential_nsdevs_1',...
      'steps_exponential_nsdevs_1',...
      'execution_time_exponential_nsdevs_1',...
      ...
      'mean_dice_coefficient_tumor_exponential_nsdevs_1',...
      'mean_sensitivity_tumor_exponential_nsdevs_1',...
      'mean_precision_tumor_exponential_nsdevs_1',...
      'mean_specificity_tumor_exponential_nsdevs_1',...
      'mean_dice_coefficient_edema_exponential_nsdevs_1',...
      'mean_sensitivity_edema_exponential_nsdevs_1',...
      'mean_precision_edema_exponential_nsdevs_1',...
      'mean_specificity_edema_exponential_nsdevs_1',...
      'mean_steps_exponential_nsdevs_1',...
      'mean_execution_time_exponential_nsdevs_1',...
      ...
      'dice_coefficient_tumor_exponential_nsdevs_2',...
      'sensitivity_tumor_exponential_nsdevs_2',...
      'precision_tumor_exponential_nsdevs_2',...
      'specificity_tumor_exponential_nsdevs_2',...
      'dice_coefficient_edema_exponential_nsdevs_2',...
      'sensitivity_edema_exponential_nsdevs_2',...
      'precision_edema_exponential_nsdevs_2',...
      'specificity_edema_exponential_nsdevs_2',...
      'steps_exponential_nsdevs_2',...
      'execution_time_exponential_nsdevs_2',...
      ...
      'mean_dice_coefficient_tumor_exponential_nsdevs_2',...
      'mean_sensitivity_tumor_exponential_nsdevs_2',...
      'mean_precision_tumor_exponential_nsdevs_2',...
      'mean_specificity_tumor_exponential_nsdevs_2',...
      'mean_dice_coefficient_edema_exponential_nsdevs_2',...
      'mean_sensitivity_edema_exponential_nsdevs_2',...
      'mean_precision_edema_exponential_nsdevs_2',...
      'mean_specificity_edema_exponential_nsdevs_2',...
      'mean_steps_exponential_nsdevs_2',...
      'mean_execution_time_exponential_nsdevs_2',...
      ...
      'dice_coefficient_tumor_exponential_nsdevs_3',...
      'sensitivity_tumor_exponential_nsdevs_3',...
      'precision_tumor_exponential_nsdevs_3',...
      'specificity_tumor_exponential_nsdevs_3',...
      'dice_coefficient_edema_exponential_nsdevs_3',...
      'sensitivity_edema_exponential_nsdevs_3',...
      'precision_edema_exponential_nsdevs_3',...
      'specificity_edema_exponential_nsdevs_3',...
      'steps_exponential_nsdevs_3',...
      'execution_time_exponential_nsdevs_3',...
      ...
      'mean_dice_coefficient_tumor_exponential_nsdevs_3',...
      'mean_sensitivity_tumor_exponential_nsdevs_3',...
      'mean_precision_tumor_exponential_nsdevs_3',...
      'mean_specificity_tumor_exponential_nsdevs_3',...
      'mean_dice_coefficient_edema_exponential_nsdevs_3',...
      'mean_sensitivity_edema_exponential_nsdevs_3',...
      'mean_precision_edema_exponential_nsdevs_3',...
      'mean_specificity_edema_exponential_nsdevs_3',...
      'mean_steps_exponential_nsdevs_3',...
      'mean_execution_time_exponential_nsdevs_3',...                            
       ...
      'dice_coefficient_tumor_linear_nsdevs_1',...
      'sensitivity_tumor_linear_nsdevs_1',...
      'precision_tumor_linear_nsdevs_1',...
      'specificity_tumor_linear_nsdevs_1',...
      'dice_coefficient_edema_linear_nsdevs_1',...
      'sensitivity_edema_linear_nsdevs_1',...
      'precision_edema_linear_nsdevs_1',...
      'specificity_edema_linear_nsdevs_1',...
      'steps_linear_nsdevs_1',...
      'execution_time_linear_nsdevs_1',...
      ...
      'mean_dice_coefficient_tumor_linear_nsdevs_1',...
      'mean_sensitivity_tumor_linear_nsdevs_1',...
      'mean_precision_tumor_linear_nsdevs_1',...
      'mean_specificity_tumor_linear_nsdevs_1',...
      'mean_dice_coefficient_edema_linear_nsdevs_1',...
      'mean_sensitivity_edema_linear_nsdevs_1',...
      'mean_precision_edema_linear_nsdevs_1',...
      'mean_specificity_edema_linear_nsdevs_1',...
      'mean_steps_linear_nsdevs_1',...
      'mean_execution_time_linear_nsdevs_1',...
            ...
      'dice_coefficient_tumor_linear_nsdevs_2',...
      'sensitivity_tumor_linear_nsdevs_2',...
      'precision_tumor_linear_nsdevs_2',...
      'specificity_tumor_linear_nsdevs_2',...
      'dice_coefficient_edema_linear_nsdevs_2',...
      'sensitivity_edema_linear_nsdevs_2',...
      'precision_edema_linear_nsdevs_2',...
      'specificity_edema_linear_nsdevs_2',...
      'steps_linear_nsdevs_2',...
      'execution_time_linear_nsdevs_2',...
      ...
      'mean_dice_coefficient_tumor_linear_nsdevs_2',...
      'mean_sensitivity_tumor_linear_nsdevs_2',...
      'mean_precision_tumor_linear_nsdevs_2',...
      'mean_specificity_tumor_linear_nsdevs_2',...
      'mean_dice_coefficient_edema_linear_nsdevs_2',...
      'mean_sensitivity_edema_linear_nsdevs_2',...
      'mean_precision_edema_linear_nsdevs_2',...
      'mean_specificity_edema_linear_nsdevs_2',...
      'mean_steps_linear_nsdevs_2',...
      'mean_execution_time_linear_nsdevs_2',...
            ...
      'dice_coefficient_tumor_linear_nsdevs_3',...
      'sensitivity_tumor_linear_nsdevs_3',...
      'precision_tumor_linear_nsdevs_3',...
      'specificity_tumor_linear_nsdevs_3',...
      'dice_coefficient_edema_linear_nsdevs_3',...
      'sensitivity_edema_linear_nsdevs_3',...
      'precision_edema_linear_nsdevs_3',...
      'specificity_edema_linear_nsdevs_3',...
      'steps_linear_nsdevs_3',...
      'execution_time_linear_nsdevs_3',...
      ...
      'mean_dice_coefficient_tumor_linear_nsdevs_3',...
      'mean_sensitivity_tumor_linear_nsdevs_3',...
      'mean_precision_tumor_linear_nsdevs_3',...
      'mean_specificity_tumor_linear_nsdevs_3',...
      'mean_dice_coefficient_edema_linear_nsdevs_3',...
      'mean_sensitivity_edema_linear_nsdevs_3',...
      'mean_precision_edema_linear_nsdevs_3',...
      'mean_specificity_edema_linear_nsdevs_3',...
      'mean_steps_linear_nsdevs_3',...
      'mean_execution_time_linear_nsdevs_3',...                                    
      ...
      'dice_coefficient_tumor_constant_nsdevs_1',...
      'sensitivity_tumor_constant_nsdevs_1',...
      'precision_tumor_constant_nsdevs_1',...
      'specificity_tumor_constant_nsdevs_1',...
      'dice_coefficient_edema_constant_nsdevs_1',...
      'sensitivity_edema_constant_nsdevs_1',...
      'precision_edema_constant_nsdevs_1',...
      'specificity_edema_constant_nsdevs_1',...
      'steps_constant_nsdevs_1',...
      'execution_time_constant_nsdevs_1',...
      ...
      'mean_dice_coefficient_tumor_constant_nsdevs_1',...
      'mean_sensitivity_tumor_constant_nsdevs_1',...
      'mean_precision_tumor_constant_nsdevs_1',...
      'mean_specificity_tumor_constant_nsdevs_1',...
      'mean_dice_coefficient_edema_constant_nsdevs_1',...
      'mean_sensitivity_edema_constant_nsdevs_1',...
      'mean_precision_edema_constant_nsdevs_1',...
      'mean_specificity_edema_constant_nsdevs_1',...
      'mean_steps_constant_nsdevs_1',...
      'mean_execution_time_constant_nsdevs_1',...
       ...
      'dice_coefficient_tumor_constant_nsdevs_2',...
      'sensitivity_tumor_constant_nsdevs_2',...
      'precision_tumor_constant_nsdevs_2',...
      'specificity_tumor_constant_nsdevs_2',...
      'dice_coefficient_edema_constant_nsdevs_2',...
      'sensitivity_edema_constant_nsdevs_2',...
      'precision_edema_constant_nsdevs_2',...
      'specificity_edema_constant_nsdevs_2',...
      'steps_constant_nsdevs_2',...
      'execution_time_constant_nsdevs_2',...
      ...
      'mean_dice_coefficient_tumor_constant_nsdevs_2',...
      'mean_sensitivity_tumor_constant_nsdevs_2',...
      'mean_precision_tumor_constant_nsdevs_2',...
      'mean_specificity_tumor_constant_nsdevs_2',...
      'mean_dice_coefficient_edema_constant_nsdevs_2',...
      'mean_sensitivity_edema_constant_nsdevs_2',...
      'mean_precision_edema_constant_nsdevs_2',...
      'mean_specificity_edema_constant_nsdevs_2',...
      'mean_steps_constant_nsdevs_2',...
      'mean_execution_time_constant_nsdevs_2',... 
       ...
      'dice_coefficient_tumor_constant_nsdevs_3',...
      'sensitivity_tumor_constant_nsdevs_3',...
      'precision_tumor_constant_nsdevs_3',...
      'specificity_tumor_constant_nsdevs_3',...
      'dice_coefficient_edema_constant_nsdevs_3',...
      'sensitivity_edema_constant_nsdevs_3',...
      'precision_edema_constant_nsdevs_3',...
      'specificity_edema_constant_nsdevs_3',...
      'steps_constant_nsdevs_3',...
      'execution_time_constant_nsdevs_3',...
      ...
      'mean_dice_coefficient_tumor_constant_nsdevs_3',...
      'mean_sensitivity_tumor_constant_nsdevs_3',...
      'mean_precision_tumor_constant_nsdevs_3',...
      'mean_specificity_tumor_constant_nsdevs_3',...
      'mean_dice_coefficient_edema_constant_nsdevs_3',...
      'mean_sensitivity_edema_constant_nsdevs_3',...
      'mean_precision_edema_constant_nsdevs_3',...
      'mean_specificity_edema_constant_nsdevs_3',...
      'mean_steps_constant_nsdevs_3',...
      'mean_execution_time_constant_nsdevs_3'... 
);








